version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: miniboard_postgres
    environment:
      POSTGRES_DB: MiniBoard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  miniboard-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: miniboard_api
    ports:
      - "5435:8080"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - VAULT_PATH=prod/apps/mini-board
    restart: unless-stopped

volumes:
  postgres_data: